# Generated by Django 4.2.30 on 2026-10-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='trabalhos/', verbose_name='Imagem')),
                ('data_servico', models.DateField(blank=True, null=True, verbose_name='Data do serviço')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabalho realizado',
                'verbose_name_plural': 'Trabalhos realizados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
