# Generated by Django 4.2.30 on 2026-10-09 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=120, verbose_name='Nome do cliente')),
                ('nota', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RemoveField(
            model_name='trabalhorealizado',
            name='data_servico',
        ),
        migrations.RemoveField(
            model_name='trabalhorealizado',
            name='imagem',
        ),
        migrations.AddField(
            model_name='trabalhorealizado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='trabalhorealizado',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='trabalhos/antes/', verbose_name='Foto antes'),
        ),
        migrations.AddField(
            model_name='trabalhorealizado',
            name='foto_depois',
            field=models.ImageField(blank=True, null=True, upload_to='trabalhos/depois/', verbose_name='Foto depois'),
        ),
        migrations.AlterField(
            model_name='trabalhorealizado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
