# Generated by Django 4.2.30 on 2026-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avaliacao_remove_trabalhorealizado_data_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhorealizado',
            name='foto_antes',
        ),
        migrations.RemoveField(
            model_name='trabalhorealizado',
            name='foto_depois',
        ),
        migrations.AddField(
            model_name='trabalhorealizado',
            name='arquivo_antes',
            field=models.FileField(blank=True, null=True, upload_to='trabalhos/antes/', verbose_name='Foto ou vídeo antes'),
        ),
        migrations.AddField(
            model_name='trabalhorealizado',
            name='arquivo_depois',
            field=models.FileField(blank=True, null=True, upload_to='trabalhos/depois/', verbose_name='Foto ou vídeo depois'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
