# Generated by Django 4.2.30 on 2026-10-09 21:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_trabalhorealizado_foto_antes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhorealizado',
            name='arquivo_antes',
            field=models.FileField(blank=True, null=True, upload_to='trabalhos/antes/', validators=[core.validators.validar_arquivo_midia], verbose_name='Foto ou vídeo antes'),
        ),
        migrations.AlterField(
            model_name='trabalhorealizado',
            name='arquivo_depois',
            field=models.FileField(blank=True, null=True, upload_to='trabalhos/depois/', validators=[core.validators.validar_arquivo_midia], verbose_name='Foto ou vídeo depois'),
        ),
    ]
